In [24]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

# 1 d array

[1 2 3]


In [25]:
arr=np.array([[1,2,3],[1,2,3]])
print("2d array",arr)
print(arr.ndim)
print(arr.size)

2d array [[1 2 3]
 [1 2 3]]
2
6


In [26]:
d1=arr.flatten()

#covert 2d arrat into the 1d array



In [27]:
d1

array([1, 2, 3, 1, 2, 3])

In [28]:
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)
print(arr.ndim)
print(arr.size)


#convert 3d into 2d
d3=arr.ravel()

d3

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3
9


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [29]:
#reshape
#convert 3d into 2d
import numpy as np
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
arr=arr.reshape(3,3)
print(arr)
print(arr.ndim)
#2d array in find silice
arr[1,1]
print(arr.ndim)
print(arr.size)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
2
2
9


In [30]:
import numpy as np
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
#rr=arr.reshape()


s=arr.ravel()

s
#print(arr)
#print(arr.ndim)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
#multiple blocks
import numpy as np
arr=np.array([[[1,2,3],[1,3,4]],[[4,5,6],[7,8,9]],[[2,5,3],[9,0,2]]])
print(arr)

In [32]:
#multiple blocks
import numpy as np
arr=np.array([[[1,2,3],[1,3,4]],[[4,5,6],[7,8,9]],[[2,5,3],[9,0,2]]])
print(arr)

[[[1 2 3]
  [1 3 4]]

 [[4 5 6]
  [7 8 9]]

 [[2 5 3]
  [9 0 2]]]
