In [2]:
import numpy as np
np.array([1,2,3])
np.array([[1,2],[3,4]])
np.zeros((2,3))
np.ones((3,3))
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [49]:
np.random.rand(3)
np.random.rand(2,2)
print(np.random.randint(1,10,5))
np.random.randn(3)

[2 7 4 6 7]


array([-1.08010483,  2.02884171, -0.02661374])

In [ ]:
arry=np.array([1, 2, 3])
print(arry)
# shape
print(arry.shape)
# size
print( arry.size)

[1 2 3]
(3,)
3


In [18]:
arr = np.array([[1,2,3],[4,5,6]],dtype=float)
arr.shape
arr.ndim
arr.size
arr.dtype
arr.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [11]:
import numpy as np
arr=np.arange(1, 10).reshape(3,3)
print(arr)
# shape,size,dimension
print("shape:",arr.shape)
print("size:",arr.size)
print("dimension:",arr.ndim)
print("2nd row:",arr[1])
print("third column:",arr[:,2])
print("center element:",arr[1][1])
print("multiply 2 with all elements:",arr*2)
print("sum of all elements:",arr.sum())
print("mean of all elements:",arr.mean())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
size: 9
dimension: 2
2nd row: [4 5 6]
third column: [3 6 9]
center element: 5
multiply 2 with all elements: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
sum of all elements: 45
mean of all elements: 5.0


In [48]:
import numpy as np
arr=np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]])

print(arr)
print(arr.ndim)
arr[0,1,1:2]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


array([5])

In [ ]:
d1=arr.ravel()





In [38]:
d1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])